# Jekyll Configuration for Manas Pandey Portfolio
title: "Manas Pandey"
description: "Physics student at IIT Kanpur exploring quantum mechanics, AI, music, and poetry"
url: "https://manasp21.github.io"
baseurl: ""

# Build settings
markdown: kramdown
highlighter: rouge
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate

# Kramdown settings
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: false

# Collections
collections:
  posts:
    output: true
    permalink: /blog/:year/:month/:day/:title/

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Manas Pandey"
      image: "/assets/og-image.jpg"
  - scope:
      path: ""
    values:
      layout: "default"
      image: "/assets/og-image.jpg"

# Site settings
author:
  name: "Manas Pandey"
  email: "manas@example.com"
  github: "manasp21"
  linkedin: "themanaspandey"

# SEO settings
lang: en_US
timezone: Asia/Kolkata
locale: en_US

# Social media profiles
social:
  name: "Manas Pandey"
  links:
    - https://github.com/manasp21
    - https://linkedin.com/in/themanaspandey
    - https://manasp21.github.io/poetry_website/

# Organization
organization:
  name: "Indian Institute of Technology Kanpur"
  url: "https://www.iitk.ac.in/"

# SEO defaults
defaults:
  - scope:
      path: ""
    values:
      image: "/assets/og-image.jpg"
      author: "Manas Pandey"

# Blog settings
excerpt_separator: <!--more-->
show_excerpts: true
paginate: 10
paginate_path: "/blog/page:num/"

# SEO Plugin Configuration
jekyll-sitemap:
  priority: 1.0
  changefreq: weekly
  lastmod: true

# Exclude from processing
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
  - .backups/
  - "*.json"
  - project_manager.py
  - blog_manager.py